apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
 name: demo-vm
spec:
 terminationGracePeriodSeconds: 0
 domain:
   resources:
     requests:
       memory: 64M
   devices:
     disks:
     - name: mydisk
       volumeName: pvcvolume
       disk:
         dev: vda
 volumes:
   - name: pvcvolume
     persistentVolumeClaim:
       claimName: demo-vm-cirros

