apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedPersistentVolumeClaim
metadata:
  name: ebs-default2
spec:
  template:
    metadata:
      name: ebs-default2
    spec:
      storageClassName: gp2
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  placement:
    clusterNames:
    - cluster2
    - cluster1
